# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da15cdb608470e79f5fcd2079125f234270ccaaf156f7e0d30a2354a2d6827bb3463c61cab2c9394f739c9629fd3477964609379b5ce34e56f873576dfb5b876

test:
  secret_key_base: c01b63369e7afecee4fc6ee9d4a71e3ba49f18f159e4c6c614452f7fd89eb7687cd0699517fbf55cdd1ae1396b562c8a9fdb372f14ed1fa0a0e25fb68284ff13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
